### ISSUE TITLE
Core dump running BAMMSC

### ISSUE THREAD

**Issue by alanocallaghan** [lichen-lab/BAMMSC#4]
After a long run time, BAMMSC gives me the following (C++, I think) error

```r
error: sort_index(): detected NaN
terminate called after throwing an instance of 'std::logic_error'
  what():  sort_index(): detected NaN
```

**Comment by inesHellmann** [comment]
I am getting the same error message. We have relatively low cell numbers/per sample. Could this be part of the issue?

**Comment by alanocallaghan** [comment]
Perhaps, I have a reasonable number of cells per sample. I'll see if I can narrow it down further

**Comment by alanocallaghan** [comment]
I get this error when trying to run the code in https://github.com/lichen-lab/BAMMSC/blob/master/HumanPBMC.md, indicating that this is a bug rather than a data issue.

**Comment by alanocallaghan** [comment]
The following code reproducibly causes a core dump: 

```r
library("mclust")
library("BAMMSC")

## Download from https://drive.google.com/open?id=1t0li4AalSRNpdLnGljhj5wJFB0JPlvm7
load("Human_PBMC.rda")
load("HumanPBMC_ApproxTruth.Rdata")
load("HumanPBMC_PooledTSNE.Rdata")

all_count <- do.call(cbind, count)
DIMMSC(all_count, K = 7)
```

The error occurs [here](https://github.com/lichen-lab/BAMMSC/blob/master/src/EM_multinomial.cpp#L154). I've not figured out the exact problem yet.

**Comment by alanocallaghan** [comment]
I think what's happening is that here: https://github.com/lichen-lab/BAMMSC/blob/master/src/EM_multinomial.cpp#L143

`den` is zero in some situations, leading to `alpha` being set to `nan`. This then propagates through the EM loop to the line linked in my previous comment.

**Comment by lichen-lab** [comment]
Hi All, I did check but did not find this issue. I suspect you may need to update the Rcpp R package. Here below is my sessionInfo to successfully run the above example,


> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] BAMMSC_1.0.0              RcppArmadillo_0.9.200.5.0
[3] Rcpp_1.0.0                dirmult_0.1.3-4
[5] mclust_5.4.1

loaded via a namespace (and not attached):
[1] compiler_3.5.1

**Comment by alanocallaghan** [comment]
I was running a more recent version of Rcpp than you (see SessionInfo below).

It also fails on R oldrel (3.5.3): https://travis-ci.org/Alanocallaghan/BAMMSC/builds/580595592
Packages used on travis were:
```
dirmult      (NA -> 0.1.3-4    ) [CRAN]
Rcpp         (NA -> 1.0.2      ) [CRAN]
RcppArmad... (NA -> 0.9.700.2.0) [CRAN]
testthat     (NA -> 2.2.1      ) [CRAN]
cli          (NA -> 1.1.0      ) [CRAN]
crayon       (NA -> 1.3.4      ) [CRAN]
digest       (NA -> 0.6.20     ) [CRAN]
evaluate     (NA -> 0.14       ) [CRAN]
magrittr     (NA -> 1.5        ) [CRAN]
praise       (NA -> 1.0.0      ) [CRAN]
R6           (NA -> 2.4.0      ) [CRAN]
rlang        (NA -> 0.4.0      ) [CRAN]
withr        (NA -> 2.1.2      ) [CRAN]
assertthat   (NA -> 0.2.1      ) [CRAN]
```

I can try to revert Rcpp to 1.0.0 to test on travis later


```
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8       
 [4] LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BAMMSC_1.0.0              RcppArmadillo_0.9.600.4.0 Rcpp_1.0.2               
[4] dirmult_0.1.3-4          

loaded via a namespace (and not attached):
 [1] rstudioapi_0.10   magrittr_1.5      usethis_1.5.1     devtools_2.1.0    pkgload_1.0.2    
 [6] R6_2.4.0          rlang_0.4.0       tools_3.6.1       pkgbuild_1.0.4    parallel_3.6.1   
[11] sessioninfo_1.1.1 cli_1.1.0         withr_2.1.2       remotes_2.1.0     assertthat_0.2.1 
[16] digest_0.6.20     rprojroot_1.3-2   crayon_1.3.4      processx_3.4.1    callr_3.3.1      
[21] fs_1.3.1          ps_1.3.0          testthat_2.2.1    memoise_1.1.0     glue_1.3.1       
[26] compiler_3.6.1    desc_1.2.0        backports_1.1.4   prettyunits_1.0.2
```

**Comment by alanocallaghan** [comment]
Btw, there are other issues with the C++ code. EG, from R CMD check:

```
File ‘BAMMSC/libs/BAMMSC.so’:
  Found ‘_ZSt4cout’, possibly from ‘std::cout’ (C++)
    Object: ‘MCMC_multinomial.o’
Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs.
```

**Comment by alanocallaghan** [comment]
Fails with Rcpp 1.0.0 as well: https://travis-ci.org/Alanocallaghan/BAMMSC/jobs/580603768

**Comment by lichen-lab** [comment]
Maybe the gcc version. We did test on linux machine cluster and Mac OS, it all works

gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by alanocallaghan** [comment]
I'm running gcc 7.4.0, I highly doubt a newer gcc version would cause this though.

**Comment by alanocallaghan** [comment]
Exact same behaviour with gcc 4.8.5.

**Comment by alanocallaghan** [comment]
@lichen-lab - I've uploaded a Singularity container containing the latest version of BAMMSC and dependencies. You can run it after installing Singularity: https://singularity.lbl.gov/

You should just need to run `singularity run image.sif`, which will launch a bash shell in the container environment. From there if you run the code below you should see the error, which will crash the R session.

The container is available here: https://uoe-my.sharepoint.com/:u:/g/personal/s1372510_ed_ac_uk/ES6liiuf0UZEuCZaxbwfckcBgTQVckcx1tdhGtJGfnaMTw?e=2CFwPp

```r
library("mclust")
library("BAMMSC")

load("Human_PBMC.rda")
load("HumanPBMC_ApproxTruth.Rdata")
load("HumanPBMC_PooledTSNE.Rdata")

set.seed(12352)
all_count <- do.call(cbind, count)

DIMMSC(all_count, K = 7)
```


Output as before:

```
Initializing clusters with kmeans clusters.
Initializing alpha matrix with Ronning method.
Performing DIMMSC clustering...

error: sort_index(): detected NaN
terminate called after throwing an instance of 'std::logic_error'
  what():  sort_index(): detected NaN
Aborted (core dumped)
```

**Comment by alanocallaghan** [comment]
Hey @lichen-lab. It seems that prior to this commit, the error would not occur: ea96cfb217a9223453f6e0579da36c085336fd72.

**Comment by alanocallaghan** [comment]
I assume this is fixed now idk
